name: "PDM update dependencies"
description: "Update the pdm.lock file"
inputs:
  token:
    description: "A personal access token"
    required: false
    default: ${{ github.token }}
  commit-message:
    description: "The commit message"
    required: false
    default: "chore: Update pdm.lock"
  pr-title:
    description: "The PR title"
    required: false
    default: "chore: Update pdm.lock"
  update-strategy:
    description: "The update strategy, can be 'reuse', 'eager' or 'all'"
    required: false
    default: "reuse"
  save-strategy:
    description: "The save strategy, can be 'compatible', 'wildcard', 'exact' or 'minimum'"
    required: false
    default: "minimum"
  unconstrained:
    description: "Ignore the version constraint of packages in pyproject.toml"
    required: false
    default: "false"
  install-plugins:
    description: "Whether install PDM plugins before update"
    required: false
    default: "false"
  sign-off-commit:
    description: "Whether commit message contains signed-off-by"
    required: false
    default: "false"
  sign-commits:
    description: "Sign commits as github-actions[bot]"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: pdm-project/setup-pdm@deb8d8a4e2a03aabcef6f2cc981923fc6b29ef99 # v4.3

    - name: Install the action plugin
      run: pdm self add ${{ github.action_path }}
      shell: bash

    - name: Install plugins
      if: inputs.install-plugins == 'true'
      run: pdm install --plugins
      shell: bash

    - name: "Update dependencies"
      run: pdm update --no-sync --update-${{ inputs.update-strategy }} --save-${{ inputs.save-strategy }} ${{ inputs.unconstrained == 'true' && '--unconstrained' || '' }}
      shell: bash
      id: pdm-update

    - id: detect-changes
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.detect-changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ inputs.commit-message }}
        signoff: ${{ inputs.sign-off-commit }}
        sign-commits: ${{ inputs.sign-commits }}
        branch: dep/update-pdm-lock
        delete-branch: true
        title: ${{ inputs.pr-title }}
        body: |
          Update locked dependencies.

          ## Update summary

          ${{ steps.pdm-update.outputs.SUMMARY }}

          *Auto-generated by [PDM update action][1]*

          [1]: https://github.com/pdm-project/update-deps-action
        labels: |
          automated pr
        draft: false

branding:
  icon: "code"
  color: "green"
