name: "PDM update dependencies"
description: "Update the pdm.lock file"
inputs:
  token:
    description: "A personal access token"
    required: false
    default: ${{ github.token }}
  commit-message:
    description: "The commit message"
    required: false
    default: "chore: Update pdm.lock"
  pr-title:
    description: "The PR title"
    required: false
    default: "chore: Update pdm.lock"
  update-strategy:
    description: "The update strategy, can be 'reuse', 'eager' or 'all'"
    required: false
    default: "reuse"
  install-plugins:
    description: "Whether install PDM plugins before update"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: pdm-project/setup-pdm@v3

    - name: Install plugins
      if: inputs.install-plugins == "true"
      run: pdm install --plugins

    - name: "Update dependencies"
      run: pdm update --no-sync --update-${{ inputs.update-strategy }}
      shell: bash

    - id: detect-changes
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: "Commit changes"
      if: steps.detect-changes.outputs.changed == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        add: pyproject.toml pdm.lock
        message: ${{ inputs.commit-message }}
        new_branch: dep/update-pdm-lock
        push: origin dep/update-pdm-lock --set-upstream --force

    - name: "Create PR"
      if: steps.detect-changes.outputs.changed == 'true'
      run: gh pr create --title "${{ inputs.pr-title }}" --body "Update pdm.lock" --head dep/update-pdm-lock || true
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

branding:
  icon: "code"
  color: "green"
